#!/bin/bash

# user-initscripts hooks

stop_user_daemons_hook() {
  local user
  for user in /run/user-daemons/*; do
    [ -d "$user" ] || continue
    su "$(basename "$user")" -c '/usr/sbin/user-rc.d stop_all'
  done
}

add_hook shutdown_start stop_user_daemons_hook
